import { env as cloudflareEnv } from "cloudflare:workers";
import { hydrateCloudflareProcessEnv } from "./src/lib/cloudflare-runtime-env";
import { resolveMaintenanceToken } from "./src/lib/maintenance-token";

type DealForgeEnv = Record<string, unknown> & {
  MAINTENANCE_TOKEN?: string;
  AUTH_SECRET?: string;
};

type ScheduledEvent = {
  cron: string;
  scheduledTime: number;
};

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

type NextWorker = {
  fetch(request: Request, env: DealForgeEnv, ctx: WorkerContext): Promise<Response>;
};

// OpenNext's generated worker and bundled server modules can evaluate
// process.env-backed constants during module initialization. Cloudflare exposes
// the exact version's text vars and secrets through the importable env object,
// so hydrate process.env before loading OpenNext. A dynamic import is required
// here: a static import/re-export would initialize OpenNext first and recreate
// the missing-runtime-secret failure this boundary is intended to prevent.
hydrateCloudflareProcessEnv(cloudflareEnv as Record<string, unknown>);

// OpenNext generates this module during the Cloudflare build.
// @ts-expect-error -- generated by OpenNext at Cloudflare build time
const nextModule = await import("./.open-next/worker.js");
const handler = nextModule.default as NextWorker;

const dealForgeWorker = {
  async fetch(request: Request, env: DealForgeEnv, ctx: WorkerContext) {
    // Re-hydrate per invocation so the request always sees the bindings attached
    // to the Worker version actually handling it. Only string values are copied.
    hydrateCloudflareProcessEnv(env);
    return handler.fetch(request, env, ctx);
  },

  async scheduled(_event: ScheduledEvent, env: DealForgeEnv, ctx: WorkerContext) {
    hydrateCloudflareProcessEnv(env);
    const token = resolveMaintenanceToken(env);
    if (!token) {
      console.error("commerce.monitor.cron_not_configured");
      return;
    }

    const request = new Request("https://www.deal-forge.sale/api/internal/commerce-monitor", {
      method: "POST",
      headers: {
        "x-dealforge-maintenance-token": token,
        "content-type": "application/json",
      },
      body: "{}",
    });

    ctx.waitUntil(
      handler.fetch(request, env, ctx).then(async (response) => {
        if (!response.ok) {
          const body = (await response.text()).slice(0, 500);
          throw new Error(`COMMERCE_MONITOR_HTTP_${response.status}:${body}`);
        }
      }),
    );
  },
};

export default dealForgeWorker;

// Preserve OpenNext durable-object exports without statically importing the
// generated module before Cloudflare bindings have hydrated process.env.
export const DOQueueHandler = nextModule.DOQueueHandler;
export const DOShardedTagCache = nextModule.DOShardedTagCache;
